FROM osrf/ros:noetic-desktop-full

SHELL ["/bin/bash", "-c"]

# Update all packages
RUN apt update && apt upgrade -y

# Install packages
RUN apt install -y \
	# already present in the base image
	# build-essential \
	# cmake \
	# libeigen3-dev \
	# libopencv-dev \
	# libprotobuf-dev \
	# libprotoc-dev \
	# libxml2-utils \
	# protobuf-compiler \
	# python3 \
	# python3-empy \
	# python3-numpy \
	# python3-rosdep \
	# python3-rosinstall \
	# python3-rospkg \
	# python3-wstool \
	# ros-noetic-rqt-common-plugins \
	# libgazebo11 \
	# extra packages
	curl \
	genromfs \
	git \
	gstreamer1.0-alsa \
	gstreamer1.0-doc \
	gstreamer1.0-gl \
	gstreamer1.0-gtk3 \
	gstreamer1.0-libav \
	gstreamer1.0-plugins-bad \
	gstreamer1.0-plugins-base \
	gstreamer1.0-plugins-good \
	gstreamer1.0-plugins-ugly \
	gstreamer1.0-pulseaudio \
	gstreamer1.0-qt5 \
	gstreamer1.0-tools \
	gstreamer1.0-x \
	libgstreamer-plugins-base1.0-dev \
	libgstreamer1.0-dev \
	ninja-build \
	python3-pip \
	qtcreator \
	wget \
	zip \
	# ros stuff, where install through apt is recommended
	python3-rosinstall-generator \
	# mavros
	ros-noetic-mavros \
	ros-noetic-mavros-extras \
	ros-noetic-rqt 

# not really needed, should be installed via pip?
# python-argparse \
# python-dev \
# python-numpy \
# python-yaml 
# python3-jinja2 \
# python3-toml \

# not installed by default
# apt-get remove modemmanager -y

# Install pip packages
RUN pip install \
	argparse \
	empy \
	jinja2 \
	jsonschema \
	numpy \
	packaging \
	pandas \
	pyserial \
	pyulog \
	pyyaml \
	toml 

# oh god why do we have python2.7 shit
# RUN pip install future 

# Rosdep update
RUN rosdep update

# Mavlink
RUN git clone --recursive --jobs 8 https://github.com/mavlink/c_library_v2.git /usr/include/c_library_v2
RUN mv /usr/include/c_library_v2/* /usr/include
RUN rm -r /usr/include/c_library_v2


# Gazebo
# the previous script installed libgazebo11 explicitly, which is already installed
# the curl command just used apt to install libgazebo11-dev and gazebo11
# both of which are already installed in the image

# PX4
RUN git clone --recursive --jobs 8 https://github.com/PX4/PX4-Autopilot.git /opt/PX4-Autopilot
RUN /opt/PX4-Autopilot/Tools/setup/ubuntu.sh
# PX4 sitl
# this is already included in PX4
# RUN git clone --recursive https://github.com/PX4/sitl_gazebo.git
# WORKDIR /root/sitl_gazebo
# RUN mkdir build
# WORKDIR /root/sitl_gazebo/build
# RUN cmake ..
# RUN make -j8
# RUN make install

# qgroundcontrol
RUN usermod -a -G dialout root
RUN wget https://d176tv9ibo4jno.cloudfront.net/latest/QGroundControl.AppImage -P /usr/bin/
RUN chmod a+x /usr/bin/QGroundControl.AppImage

# MavROS
# already installed earlier with apt

# Dont need to source the ROS entrypoint file, already done in the base image
# RUN source /ros_entrypoint.sh

WORKDIR /root

ENV SHELL /bin/bash

CMD ["/bin/bash"]
