version: "2"


services:
  linux:
    image: maav-mission9
    privileged: true
    volumes:
      - .:/mission9-2021:rw  # Copy code into Docker container
      - $HOME/.Xauthority:/root/.Xauthority:rw
        #- /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1yy
    network_mode: "host"
    container_name: maav-mission9
    command: "/bin/bash --init-file scripts/source-ros.sh"

  wsl:
    image: maav-mission9
    privileged: true
    ports:
      - 5900:5900
      - 6080:80
    volumes:
      - .:/mission9-2021:rw  # Copy code into Docker container
    #   - /tmp/.X11-unix:/tmp/.X11-unix
    # environment:
    #   - DISPLAY
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
      - /dev/video2:/dev/video2
      - /dev/video3:/dev/video3
      - /dev/video4:/dev/video4
      - /dev/video5:/dev/video5
      - /dev/media0:/dev/media0
      - /dev/media1:/dev/media1
    container_name: maav-mission9
    command: "/bin/bash --init-file scripts/source-ros.sh"

  mac:
    image: maav-mission9
    privileged: true
    ports:
        - 5900:5900
        - 6080:80
    volumes:
        - .:/mission9-2021:rw # Copy code into Docker container
    network_mode: "host"
    container_name: maav-mission9
    command: "/bin/bash --init-file scripts/source-ros.sh"

